# Generated by Django 6.0.1 on 2026-02-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_conversation_is_deleted_message_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
    ]
