# Generated by Django 6.0.1 on 2026-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_last_seen',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'My Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_profile_photo',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('contacts', 'My Contacts'), ('nobody', 'Nobody')], default='everyone', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_read_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_auto_download_media',
            field=models.BooleanField(default=True),
        ),
    ]
