# Generated by Django 6.0.1 on 2026-01-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_app_language_user_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_wallpaper',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_groups_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_disappearing_messages_timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='security_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_step_verification_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
