# Generated by Django 6.0.1 on 2026-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blockeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_wallpaper',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
